version = "0.2"
license = "GPL"
package = "sysdyn"
title = "System Dynamics"
authors = "Gilberto Camara and Pedro R. Andrade"
contact = "pedro.andrade@inpe.br"
content = "Implements a System Dynamics framework."
