version = "0.6.4"
license = "GPL"
package = "sysdyn"
depends = "terrame (>= 2.0), sci (>= 0.3)"
title = "System Dynamics"
authors = "Gilberto Camara and Pedro R. Andrade"
contact = "pedro.andrade@inpe.br"
content = "Implements a System Dynamics framework."
