version = "0.1"
license = "GPL"
package = "sysdyn"
title = "System Dynamics"
date = "17 July 2015"
authors = "Gilberto Camara and Pedro R. Andrade"
contact = "pedro.andrade@inpe.br"
content = "Implements a System Dynamics framework."
